---

- name: copy master systemd start scripts
  template:
    src: "spark-master-systemd.j2"
    dest: /etc/systemd/system/spark-master.service
    owner: root
    group: root
  become: true
  when: inventory_hostname in groups['spark-masters']
  notify:
    - restart spark-master
  tags: spark-node

- name: copy worker systemd start scripts
  template:
    src: "spark-worker-systemd.j2"
    dest: /etc/systemd/system/spark-worker.service
    owner: root
    group: root
  become: true
  when: inventory_hostname in groups['spark-workers']
  notify:
    - restart spark-worker
  tags: spark-node

- name: start spark masters
  service: name=spark-master state=started enabled=yes
  when: inventory_hostname in groups['spark-masters']
  become: true

- name: start spark workers
  service: name=spark-worker state=started enabled=yes
  when: inventory_hostname in groups['spark-workers']
  become: true